import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Product from "../components/home/product";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Shop Online</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Product />
      </main>
    </div>
  );
};

export default Home;
